In [69]:
import numpy as np
import os


In [70]:
 # - 一维数组 List1 = [1, 2, 3]
 # - 二维数http://192.168.99.42:8888/notebooks/keras/ResNet50_wirking%20on.ipynb#组 Tuple1 = ([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [71]:
x = np.array([1]) # 建立一个一维矩阵x, x.shape 为矩阵的长度
x.shape #shape函数是numpy.core.fromnumeric中的函数，它的功能是查看矩阵或者数组的维数。


(1,)

In [72]:
x = np.array([1,2]) # 建立一个一维矩阵x, x.shape 为矩阵的长度
x.shape #shape函数是numpy.core.fromnumeric中的函数，它的功能是查看矩阵或者数组的维数。


(2,)

In [73]:
x = np.array([1,2,3]) # 建立一个一维矩阵x, x.shape 为矩阵的长度
x.shape #shape函数是numpy.core.fromnumeric中的函数，它的功能是查看矩阵或者数组的维数。


(3,)

In [74]:
x = np.array([[1,2,7,8],[1,4,5,3],[1,2,5,6]]) # 建立一个一维矩阵x, x.shape 为矩阵的长度
x.shape #xshape = (3, 4) 有三個大單位,,每個單位有4筆資料。 


(3, 4)

In [75]:
x = np.array([[[1,2,7,8],[1,4,5,3],[1,2,5,6]]]) # 建立一个一维矩阵x, x.shape 为矩阵的长度
x.shape # xshape =(1, 3, 4)  有1個大單位,每個大單位有3筆小單位,每個小單位有4筆資料。 

(1, 3, 4)

In [76]:
x = np.array([[  [1,2,7,8],[1,4,5,3],[1,2,5,6],  ],
              [  [1,2,7,8],[1,4,5,3],[1,2,5,6]   ]
             ]) # 建立一个一维矩阵x, x.shape 为矩阵的长度
x.shape # xshape =(1, 3, 4)  有1個大單位,每個大單位有3筆小單位,每個小單位有4筆資料。 

(2, 3, 4)

In [77]:


print( x)

[[[1 2 7 8]
  [1 4 5 3]
  [1 2 5 6]]

 [[1 2 7 8]
  [1 4 5 3]
  [1 2 5 6]]]


In [78]:
x_dims = np.expand_dims(x, axis=0)


In [79]:
x_dims.shape

(1, 2, 3, 4)

In [80]:
print(x_dims)

[[[[1 2 7 8]
   [1 4 5 3]
   [1 2 5 6]]

  [[1 2 7 8]
   [1 4 5 3]
   [1 2 5 6]]]]


In [81]:
x = np.array([1,2]) # 建立一个一维矩阵x, x.shape 为矩阵的长度
x.shape

(2,)

In [82]:
print(x)

[1 2]


In [83]:
x_a = np.expand_dims(x, axis=0)
x_a.shape  

(1, 2)

In [84]:
print(x_a)

[[1 2]]


In [85]:
x_a2 = np.expand_dims(x_a, axis=0)
x_a2.shape  

(1, 1, 2)

In [86]:
print(x_a2)

[[[1 2]]]


In [87]:
x_a3 = np.expand_dims(x_a2, axis=1)
x_a3.shape  

(1, 1, 1, 2)

In [88]:
print(x_a3)

[[[[1 2]]]]


In [89]:
x = np.array([1,2]) # 建立一个一维矩阵x, x.shape 为矩阵的长度
x.shape

(2,)

In [90]:
print(x)

[1 2]


In [91]:
x_a = np.expand_dims(x, axis=0)
x_a.shape  

(1, 2)

In [92]:
print(x_a)

[[1 2]]


In [93]:
x_a = np.expand_dims(x_a, axis=1)
x_a.shape  

(1, 1, 2)

In [94]:
print(x_a)

[[[1 2]]]
